---
- name: nginx conf message
  debug:
    msg: "The variable nginx_custom_confs_path is mandatory to deploy other nginx confs"
  when: nginx_custom_confs_path is undefined

- name: Create nginx user
  user:
    name: nginx
    group: nginx

- name: Create nginx directories
  file:
    path: "{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
  loop:
    - /opt/nginx
    - /opt/nginx/nginx.d

- name: Create nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: root
    group: logs-readers
    mode: 0755

- name: Set log files
  file:
    path: "{{ item }}"
    state: touch
    owner: nginx
    group: nginx
    mode: 0755
  loop:
    - /var/log/nginx/error.log
    - /var/log/nginx/access.log

- name: Upload the docker-compose.yml file
  template:
    src: "templates/docker-compose.yaml.j2"
    dest: "/opt/nginx/docker-compose.yaml"
    owner: nginx
    group: nginx

- name: Upload the nginx.conf file
  copy:
    src: "{{ nginx_default_conf_path }}"
    dest: /opt/nginx/nginx.conf
    owner: nginx
    group:  nginx

- name: Upload nginx custom confs
  copy:
    src: "{{ nginx_custom_confs_path }}/"
    dest: /opt/nginx/nginx.d
  when: nginx_custom_confs_path is defined

- name: Launch nginx container
  community.docker.docker_compose_v2:
    project_src: "/opt/nginx/"
    state: present